apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: $(cat $SSH_PRIVATEKEY_PATH | base64 -w 0) # ... base64-encoded private key ...
  known_hosts: $(cat tmp.txt |base64 -w 0) # ... base64-encoded known_hosts file …
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-admin
secrets:
  - name: git-credentials
