apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: clone-read-run-listener
spec:
  serviceAccountName: clone-read-run-sa
  triggers:
    - name: clone-read-run-el
      bindings:
        - ref: clone-read-run-binding
      template:
        ref: clone-read-run-template
