apiVersion: v1
kind: Pod
metadata:
  name: sample-nodename-ubuntu-master
  labels:
    app: ubuntu-service
spec:
  containers:
  - name: sample-nodename-ubuntu-master
    image: ubuntu:latest
    command:
      - sleep
      - infinity
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: ubuntu-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080