apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  storageClassName: redis-storage
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.global.redis.capacity }}Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.redis.parent_path}}{{ .Values.global.redis.filename}}
    type: DirectoryOrCreate # ディレクトリが存在しない場合は作成
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.global.namespace}}
spec:
  storageClassName: redis-storage
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.global.redis.capacity }}Gi
